server:
  port: 9997
  context-path: /clientOne
security:
  user:
    password: 123456
  oauth2:
    client:
      client-id: owen
      client-secret: owen 
      user-authorization-uri: http://130.75.131.236:8000/auth/oauth/authorize    
      access-token-uri: http://130.75.131.236:8000/auth/oauth/token
    resource: 
        user-info-uri: http://130.75.131.236:8000/auth/users #返回认证服务器检查
        prefer-token-info: false
 
 
spring:
  application:
    name: open-auth-sso
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name:  oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#      username: crm_owner_user
#      password: bss_crm_test
#      filters: stat,wall
################## mysql start ############################
      driver-class-name:  com.mysql.jdbc.Driver
      #     192.168.3.150   130.75.131.211
      url: jdbc:mysql://130.75.131.211:3306/oauth2-security?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 1q2w3e4r
      filters: stat,wall
################### mysq end l##########################
  redis:
################### redis 单机版 start ########################## 
#    host: 127.0.0.1
#    port: 6379    
#    timeout: 3000
#    database: 1
################### redis 单机版 end ##########################   
    cluster:
      nodes: 130.75.131.237:7000,130.75.131.238:7000,130.75.131.239:7000,130.75.131.237:7001,130.75.131.238:7001,130.75.131.239:7001
##        #130.75.131.237:7000,130.75.131.238:7000,130.75.131.239:7000,130.75.131.237:7001,130.75.131.238:7001,130.75.131.239:7001
#        #192.168.3.157:7000,192.168.3.158:7000,192.168.3.159:7000,192.168.3.157:7001,192.168.3.158:7001,192.168.3.159:7001
    timeout: 1000 # 连接超时时间（毫秒）
    pool:
      max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8     # 连接池中的最大空闲连接
      min-idle: 2     # 连接池中的最小空闲连接
      max-wait: 100   # 连接池最大阻塞等待时间（使用负值表示没有限制）     
    
    

mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:com/open/**/dao/*.xml  
 
